### ISSUE TITLE
Elaborate the use cases

### ISSUE THREAD

**Issue by julkue** [paulsonnentag/swip#50]
I'm interested in the idea behind this project and its use cases. These information are missing in the documentation. An example answer could be to whom this project aims.

**Comment by paulsonnentag** [comment]
This started out as a hackathon project. The inspiration came from [siftables](https://www.youtube.com/watch?v=JP0w9lZoLwU), which are little programmable diplay squares that can sense how they are position relative to each other. We wanted to build the same kind of applications without having to create custom hardware. It's more intended as an experiment to play around with new ideas rather than solving a concrete problem. If you have some greate ideas for applications let us know. Right now we are not actively working on the project though.

**Comment by timgrossmann** [comment]
When thinking about some use cases, you are not restricted to using the canvas element (which we used for the demos). You can also use a standard webpage on which you can react on the swipe events. 
A pretty nice "copycat"-project would be the popular bump-app in the browser where you can set up your contact information and exchange them with others with a simple swipe... 
If you're building for example a trading card game, you could add social interactions by giving the players some perks if they exchange cards locally when "swiped" together.
If you have an application like PayPal where you can send money to friends, you could increase the usability for the customers by giving them some kind of physical interaction (the swipe).

There are really a lot of possibilities, since it's built as a library you could integrate it with a lot of different applications and give them some nice unique features, it's not restricted to games.
